# Generated by Django 3.2.16 on 2022-12-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheGoodChat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('2022', '2022'), ('2021', '2021'), ('1975', '1975')], default='2000', max_length=100),
        ),
    ]
